version: '3.8'

services:
  web_server:
    stdin_open: true
    build:
      context: Chess_Opening_Trainer_Frontend
    expose:
      - 80
    ports:
      - 8080:80
    depends_on:
      - api_server

  api_server:
      build: 
        context: Chess_Opening_Trainer_Backend
      ports:
        - "3000:3000"
      networks:
        - chess_opening_trainer_network
      depends_on:
        - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: chess_opening_trainer_db_user
      POSTGRES_PASSWORD: S@5xS^JsyvUH!9
      POSTGRES_DB: chess_opening_trainer_db
    ports:
      - "5433:5432"
    networks:
      - chess_opening_trainer_network
    volumes:
      - chess_opening_trainer_volume:/var/lib/postgresql/data

networks:
  chess_opening_trainer_network:
    driver: bridge

volumes:
  chess_opening_trainer_volume:
